name: rq_soap
description: QR SoaP
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  logger: 1.2.2
  shared_preferences: ^2.0.17
  flutter_bloc: 8.1.2
  equatable: 2.0.5
  bloc: 8.1.1
  dio: 4.0.6
  get_it: 7.2.0
  animate_do: ^3.0.2
  getwidget: ^2.0.4
  font_awesome_flutter: 10.4.0
  animated_splash_screen: 1.3.0
  loading_animation_widget: ^1.2.0+4
  material_dialogs: ^1.1.4
  dotted_border: ^2.1.0
  device_uuid: ^0.0.4
  flutter_image_slideshow: ^0.1.6
  flutter_svg: ^2.0.9
  flutter_qr_bar_scanner: 3.0.2
  flutter_secure_storage: 6.0.0
  http: ^0.13.6
  http_parser: ^4.0.0
  card_swiper: 3.0.0
  url_launcher: 6.1.8
  date_picker_plus: 2.1.0
  sign_in_button: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons:
    git:
      url: https://github.com/fluttercommunity/flutter_launcher_icons.git
      ref: 26fedcee4b0e6f7a85f65f1fb48834a21f57e970

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/iconApp.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
